const APP_SETTINGS = {
    OUTPUT_PATH: 'output',
    POKEMON_FILE: 'pokemon.json',
    TYPE_FILE: 'type.json',
    MOVE_FILE: 'move.json',
    AVATAR_CUSTOMIZATION_FILE: 'avatar-customization.json',
    MAX_CP_MULTIPLIER: 0.79030001,
    MAX_INDIVIDUAL_STAMINA: 15,
    MAX_INDIVIDUAL_ATTACK: 15,
    MAX_INDIVIDUAL_DEFENSE: 15,
    POKEMON_TYPES: [
        { attackScalarIndex: 0,
          id: 'POKEMON_TYPE_NORMAL' },
        { attackScalarIndex: 1,
          id: 'POKEMON_TYPE_FIGHTING' },
        { attackScalarIndex: 2,
          id: 'POKEMON_TYPE_FLYING' },
        { attackScalarIndex: 3,
          id: 'POKEMON_TYPE_POISON' },
        { attackScalarIndex: 4,
          id: 'POKEMON_TYPE_GROUND' },
        { attackScalarIndex: 5,
          id: 'POKEMON_TYPE_ROCK' },
        { attackScalarIndex: 6,
          id: 'POKEMON_TYPE_BUG' },
        { attackScalarIndex: 7,
          id: 'POKEMON_TYPE_GHOST' },
        { attackScalarIndex: 8,
          id: 'POKEMON_TYPE_STEEL' },
        { attackScalarIndex: 9,
          id: 'POKEMON_TYPE_FIRE' },
        { attackScalarIndex: 10,
          id: 'POKEMON_TYPE_WATER' },
        { attackScalarIndex: 11,
          id: 'POKEMON_TYPE_GRASS' },
        { attackScalarIndex: 12,
          id: 'POKEMON_TYPE_ELECTRIC' },
        { attackScalarIndex: 13,
          id: 'POKEMON_TYPE_PSYCHIC' },
        { attackScalarIndex: 14,
          id: 'POKEMON_TYPE_ICE' },
        { attackScalarIndex: 15,
          id: 'POKEMON_TYPE_DRAGON' },
        { attackScalarIndex: 16,
          id: 'POKEMON_TYPE_DARK' },
        { attackScalarIndex: 17,
          id: 'POKEMON_TYPE_FAIRY' }
    ]
};

export default APP_SETTINGS;
